import type { ProjectProps } from "@/types";

export const PROJECTS: ProjectProps[] = [
  {
    name: "SeaBaas Mizan",
    image: "/assets/images/placeholder.png",
    url: "",
    color: "#36A955",
    type: "nda",
    year: "2025",
  },
  {
    name: "Southern Ontario Dental College",
    image: "/assets/images/placeholder.png",
    url: "",
    color: "#491B64",
    type: "nda",
    year: "2025",
  },
  {
    name: "Classore",
    image: "/assets/images/classore.png",
    url: "https://classore.com",
    color: "#6F42C1",
    type: "contract",
    year: "2024",
  },
  {
    name: "Gazelle by Sterling",
    image: "/assets/images/placeholder.png",
    url: "",
    color: "#203803",
    type: "nda",
    year: "2024",
  },
  {
    name: "CommunityPro",
    image: "/assets/images/community-pro.png",
    url: "https://community-pro-web.vercel.app",
    color: "#FFCD42",
    type: "open source",
    year: "2024",
  },
  {
    name: "Bettercareer",
    image: "/assets/images/bettercareer.png",
    url: "https://www.bettercareer.me",
    color: "#3198F8",
    type: "open source",
    year: "2024",
  },
  {
    name: "Datarango",
    image: "/assets/images/datarango.png",
    url: "https://datarango.com",
    color: "#E6651F",
    type: "contract",
    year: "2024",
  },
  {
    name: "Zummit Africa",
    image: "/assets/images/zummit-africa.png",
    url: "https://zummitafrica.com",
    color: "#5A284E",
    type: "contract",
    year: "2023",
  },
  {
    name: "Color Zen",
    image: "/assets/images/color-zen.png",
    url: "https://color-zen.vercel.app",
    color: "#fea630",
    type: "side project",
    year: "2023",
  },
  {
    name: "TraxoHQT",
    image: "/assets/images/traxo-hqt.png",
    url: "https://traxo-hq.vercel.app",
    color: "#",
    type: "side project",
    year: "2023",
  },
  {
    name: "Foglio",
    image: "/assets/images/foglio.png",
    url: "https://foglio.vercel.app",
    color: "#56DB9C",
    type: "side project",
    year: "2023",
  },
  {
    name: "Traxo Finance",
    image: "/assets/images/traxo-finance.png",
    url: "https://master.d16z9rxqclx4lm.amplifyapp.com",
    color: "#151515",
    type: "side project",
    year: "2021",
  },
];
